### ISSUE TITLE
Segmentation fault when create text group chat (multidevice)

### ISSUE THREAD

**Issue by davidak** [GrayHatter/uTox#370]
steps to reproduce:

1. have 2 instances of uTox running, connected as one User
2. create a text group chat in one instance
3. (it doesn't get synced to the other instance)
4. (sent text doesn't appear in chat)
5. restart other instance
6. instance with group chat crashes (segfault) (sometimes you have to move the cursor over the GUI or repeat restarting the other instance)

`strace -fy ./utox`:

```
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 317907779}) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 317945479}) = 0
[pid  3536] ioctl(21<socket:[27066]>, FIONREAD, [51]) = 0
[pid  3536] recvfrom(21<socket:[27066]>, "\0001", 2, MSG_NOSIGNAL, NULL, NULL) = 2
[pid  3536] ioctl(21<socket:[27066]>, FIONREAD, [49]) = 0
[pid  3536] recvfrom(21<socket:[27066]>, "9d\264\7\220}\304JG\267\257efh\343[\204\306\r\331\323\250\350'\320\342\305\271Ha\273\370"..., 49, MSG_NOSIGNAL, NULL, NULL) = 49
[pid  3536] write(1</dev/pts/0>, "handle_packet MDEV dev_num 0 // "..., 64handle_packet MDEV dev_num 0 // dev_id 0 // pkt 37 // length 2 
) = 64
[pid  3536] sendto(21<socket:[27066]>, "\0001*u9\241\24\257\3758\235L#\262\272\275\3\245\2628\360\375\300j\271<o\305\34\31\4\23"..., 51, MSG_NOSIGNAL, NULL, 0) = 51
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 318479177}) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 318562732}) = 0
[pid  3536] write(1</dev/pts/0>, "friend list change, updating ros"..., 36friend list change, updating roster
) = 36
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 318770024}) = 0
[pid  3536] ioctl(21<socket:[27066]>, FIONREAD, [0]) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 318896549}) = 0
[pid  3536] ioctl(17<socket:[27068]>, FIONREAD, [0]) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 319026685}) = 0
[pid  3536] ioctl(15<socket:[27070]>, FIONREAD, [0]) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 319152933}) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 319207604}) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 319264113}) = 0
[pid  3536] nanosleep({0, 20000000},  <unfinished ...>
[pid  3538] <... nanosleep resumed> NULL) = 0
[pid  3538] nanosleep({0, 50000000},  <unfinished ...>
[pid  3533] <... poll resumed> )        = 1 ([{fd=3, revents=POLLIN}])
[pid  3533] recvmsg(3<socket:[30870]>,  <unfinished ...>
[pid  3536] <... nanosleep resumed> NULL) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 339488858}) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW,  <unfinished ...>
[pid  3533] <... recvmsg resumed> {msg_name(0)=NULL, msg_iov(1)=[{"\6\0\374'v\224\263\0\201\2\0\0\1\0\200\2\0\0\0\0\243\2\360\0[\2\227\0\0\0\1\0", 4096}], msg_controllen=0, msg_flags=0}, 0) = 32
[pid  3536] <... clock_gettime resumed> {11766, 339532672}) = 0
[pid  3536] recvfrom(13<socket:[27051]>,  <unfinished ...>
[pid  3533] recvmsg(3<socket:[30870]>,  <unfinished ...>
[pid  3536] <... recvfrom resumed> 0x7f70ab63c4f0, 2048, 0, 0x7f70ab63c470, 0x7f70ab63c44c) = -1 EAGAIN (Resource temporarily unavailable)
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW,  <unfinished ...>
[pid  3533] <... recvmsg resumed> 0x7ffe83c872c0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid  3536] <... clock_gettime resumed> {11766, 339694341}) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 339721241}) = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW,  <unfinished ...>
[pid  3533] poll([{fd=3<socket:[30870]>, events=POLLIN|POLLOUT}], 1, -1 <unfinished ...>
[pid  3536] <... clock_gettime resumed> {11766, 339769022}) = 0
[pid  3536] ioctl(21<socket:[27066]>, FIONREAD <unfinished ...>
[pid  3533] <... poll resumed> )        = 1 ([{fd=3, revents=POLLOUT}])
[pid  3536] <... ioctl resumed> , [0])  = 0
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 339911555}) = 0
[pid  3533] writev(3<socket:[30870]>, [{"\2\0\4\0\1\0\200\2\0@\0\0\267\0\200\2", 16}, {NULL, 0}, {"", 0}], 3 <unfinished ...>
[pid  3536] ioctl(17<socket:[27068]>, FIONREAD, [0]) = 0
[pid  3533] <... writev resumed> )      = 16
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 340017013}) = 0
[pid  3536] ioctl(15<socket:[27070]>, FIONREAD <unfinished ...>
[pid  3533] recvmsg(3<socket:[30870]>,  <unfinished ...>
[pid  3536] <... ioctl resumed> , [0])  = 0
[pid  3533] <... recvmsg resumed> 0x7ffe83c872d0, 0) = -1 EAGAIN (Resource temporarily unavailable)
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 340395209}) = 0
[pid  3533] --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x10} ---
[pid  3536] clock_gettime(CLOCK_MONOTONIC_RAW, {11766, 340528927}) = 0
[pid  3539] +++ killed by SIGSEGV (core dumped) +++
[pid  3538] +++ killed by SIGSEGV (core dumped) +++
[pid  3537] +++ killed by SIGSEGV (core dumped) +++
[pid  3536] +++ killed by SIGSEGV (core dumped) +++
[pid  3535] +++ killed by SIGSEGV (core dumped) +++
[pid  3534] +++ killed by SIGSEGV (core dumped) +++
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

---

[build #14](https://build.tox.chat/view/uTox/job/uTox-multidevice_build_linux_x86-64_debug/14/) of uTox-multidevice_build_linux_x86-64_debug (version 0.9.5)
tested on elementary OS Freya (Ubuntu 12.04 based) and Loki (Ubuntu 16.04 based)

**Comment by GrayHatter** [comment]
@davidak I'm pretty sure this is a uTox issue, not a groupchat issue

also groupchats don't sync yet

**Comment by GrayHatter** [comment]
@davidak sorry, I though you opened this on the toxcore repo... this is fixed now

**Comment by davidak** [comment]
it still crashes in last build #1​6 from 25.06.2016 19:08

**Comment by GrayHatter** [comment]
this should be fixed now, let me know if it's not

**Comment by davidak** [comment]
still not fixed.

tested **Build 38 (14.07.2016 17:36:30)** on elementary OS Loki Beta 2 (Ubuntu 16.04 based)

i completely installed 3 new linux VMs since i already deleted the last ones i used for testing.

are you able to reproduce this now?

https://youtu.be/cE4TIJxRG5g
